Repository graasp/graasp-builder, pull requests merged in 2021-08, with the labels that each got.

#191 refactor: remove obsolete websocket calls, update query-client
  cypress/integration/ws/item.spec.js
  package.json
  src/components/SharedItems.js
  src/components/item/ItemContent.js
  src/config/queryClient.js
  yarn.lock
Labels: feature

#195 fix: discard changes when the modal is closed
  src/components/context/EditItemModalContext.js
Labels: bug

#186 181/oneLineNameDisplay
  src/components/common/SettingsHeader.js
  src/config/constants.js
  yarn.lock
Labels: refactor

#196 165/copy move multiple
  cypress/fixtures/items.js
  cypress/integration/item/copy/gridCopyItem.spec.js
  cypress/integration/item/copy/listCopyItem.spec.js
  cypress/integration/item/copy/listCopyMultiple.spec.js
  cypress/integration/item/move/gridMoveItem.spec.js
  cypress/integration/item/move/listMoveItem.spec.js
  cypress/integration/item/move/listMoveMultiple.spec.js
  cypress/support/commands.js
  cypress/support/server.js
  src/components/common/MoveButton.js
  src/components/context/CopyItemModalContext.js
  src/components/context/CreateShortcutModalContext.js
  src/components/context/MoveItemModalContext.js
  src/components/main/CopyButtons.js
  src/components/main/ItemMenu.js
  src/components/main/TableToolbar.js
  src/components/main/TreeModal.js
  src/config/messages.js
  src/config/selectors.js
  src/middlewares/notifier.js
Labels: feature
