Repository graasp/graasp-builder, pull requests merged in 2023-03, with the labels that each got.

#581 490 fix sentry version
  README.md
  package.json
  src/config/constants.ts
  src/index.tsx
  yarn.lock
Labels: bug, chore, improvement

#562 feat: add document styles in Builder
  package.json
  src/components/common/CollapseButton.tsx
  src/components/common/DeleteButton.tsx
  src/components/common/FavoriteButton.tsx
  src/components/common/HideButton.tsx
  src/components/common/MoveButton.tsx
  src/components/common/PinButton.tsx
  src/components/common/RecycleButton.tsx
  src/components/item/ItemContent.tsx
  src/components/item/form/DocumentForm.tsx
  src/components/main/CopyButton.tsx
  src/components/main/ItemMenu.tsx
  src/config/constants.ts
  src/utils/itemExtra.ts
  yarn.lock
Labels: feature

#588 fix: use `CustomInitialLoader` on first load
  src/components/App.tsx
Labels: bug, improvement

#593 feat: bump @graasp/sdk
  package.json
  src/components/common/CollapseButton.tsx
  src/components/common/EditButton.tsx
  src/components/common/HideButton.tsx
  src/components/common/PinButton.tsx
  src/components/context/CreateShortcutModalContext.tsx
  src/components/context/EditItemModalContext.tsx
  src/components/item/form/BaseItemForm.tsx
  src/components/item/form/FolderForm.tsx
  src/components/main/Item.tsx
  src/components/main/ItemMenu.tsx
  src/components/main/ItemsTable.tsx
  src/components/main/ItemsToolbar.tsx
  src/components/main/Main.tsx
  src/components/main/NewItemModal.tsx
  src/components/table/ActionsCellRenderer.tsx
  src/utils/item.ts
  yarn.lock
Labels: feature

#600 build: remove un-used Dockerfiles
  .productioncontainer/docker-compose.yml
  Dockerfile
  Dockerfile.build.dev
  Dockerfile.build.prod
  Dockerfile.prod
Labels: build, chore

#591 feat: highlight item status with badges
  cypress/e2e/item/hide/hideItem.cy.js
  cypress/e2e/item/view/viewFolder.cy.js
  cypress/support/commands.js
  cypress/support/server.js
  package.json
  src/components/common/FavoriteButton.tsx
  src/components/common/HideButton.tsx
  src/components/main/ItemCard.tsx
  src/components/main/Items.tsx
  src/components/main/ItemsGrid.tsx
  src/components/main/ItemsTable.tsx
  src/components/table/BadgesCellRenderer.tsx
  src/config/constants.ts
  src/config/selectors.ts
  src/utils/item.ts
  src/utils/itemTag.js
  src/utils/itemTag.ts
  yarn.lock
Labels: feature, improvement
