Repository graasp/graasp-builder, pull requests merged in 2023-12, with the labels that each got.

#882 fix: autofocus search field in appform and fix box shrinking
  src/components/item/form/AppForm.tsx
  src/components/item/form/NameForm.tsx
Labels: bug :beetle:

#908 feat: navigate to the item on short link click
  src/components/item/sharing/shortLink/ShortLink.tsx
Labels: feature

#757 fix(link): allow all non-whitespace chars in urls
  src/utils/item.ts
Labels: bug :beetle:

#922 fix: allow apps to resize
  src/components/item/ItemContent.tsx
Labels: improvement
