Repository graasp/graasp-builder, pull requests merged in 2023-10, with the labels that each got.

#805 chore: bump graasp-ui and remove signOut prop
  .github/workflows/cypress.yml
  package.json
  src/components/main/ItemScreen.tsx
  yarn.lock
Labels: chore

#812 feat: App card's style enhancement
  cypress/support/commands/item.ts
  src/components/item/form/AppForm.tsx
  src/components/item/form/NameForm.tsx
  src/components/main/AppCard.tsx
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/en.json
Labels: improvement

#802 feat: integrate websockets updates
  .github/workflows/cypress.yml
  package.json
  src/components/App.tsx
  src/components/RecycleBinScreen.tsx
  yarn.lock
Labels: feature

#833 fix: use `??` instead of `||` for skeleton in `AppCard.tsx`
  src/components/main/AppCard.tsx
Labels: bug :beetle:, ui :eyes:

#822 feat: create a dialog to downgrade own membership
  package.json
  src/components/item/sharing/ItemMembershipSelect.tsx
  src/components/item/sharing/ItemMembershipsTable.tsx
  src/components/item/sharing/TableRowPermissionRenderer.tsx
  src/config/selectors.ts
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/en.json
  yarn.lock
Labels: improvement
