Repository graasp/graasp-builder, pull requests merged in 2024-01, with the labels that each got.

#944 fix: fix reorder in table
  src/components/main/ItemsTable.tsx
Labels: bug :beetle:

#948 fix: remove email freq enum
  src/config/constants.ts
  src/config/selectors.ts
Labels: chore

#949 fix: update chatbox
  package.json
  src/components/common/Chatbox.tsx
  yarn.lock
Labels: dependencies

#959 fix: fix visibility select lang translations
  src/langs/ar.json
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
Labels: bug :beetle:

#966 fix: update crop modal
  cypress/e2e/item/create/createShortcut.cy.ts
  cypress/e2e/item/delete/gridRecycleItem.cy.ts
  cypress/e2e/item/delete/listDeleteItem.cy.ts
  cypress/e2e/item/delete/listDeleteItems.cy.ts
  cypress/e2e/item/delete/listRecycleItem.cy.ts
  cypress/e2e/item/delete/listRecycleItems.cy.ts
  cypress/e2e/item/edit/editFolder.cy.ts
  cypress/e2e/item/favorite/favoriteItem.cy.ts
  cypress/e2e/item/home/home.cy.ts
  cypress/e2e/item/move/listMoveItem.cy.ts
  cypress/e2e/item/move/listMoveMultiple.cy.ts
  cypress/e2e/item/pin/pinItem.cy.ts
  cypress/support/commands/navigation.ts
  cypress/support/constants.ts
  cypress/support/editUtils.ts
  cypress/support/server.ts
  package.json
  src/components/common/CropModal.tsx
  src/components/item/settings/ThumbnailSetting.tsx
  src/config/notifier.ts
  src/config/queryClient.ts
  src/langs/constants.ts
  src/langs/en.json
  src/utils/image.ts
  yarn.lock
Labels: bug :beetle:, improvement

#968 fix: update main component and cleanup
  cypress/e2e/item/edit/editApp.cy.ts
  cypress/e2e/item/publish/coEditorSettings.cy.ts
  cypress/e2e/item/settings/itemSettings.cy.ts
  cypress/support/editUtils.ts
  package.json
  src/components/Root.tsx
  src/components/common/EditButton.tsx
  src/components/item/ItemMain.tsx
  src/components/main/Main.tsx
  src/langs/constants.ts
  src/langs/en.json
  src/langs/fr.json
  yarn.lock
Labels: feature
