Repository graasp/graasp-builder, pull requests merged in 2024-11, with the labels that each got.

#1560 chore(main): release 2.45.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1564 chore(main): release 2.46.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1570 chore(main): release 2.47.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1574 chore(main): release 2.47.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1578 fix: remove display name
  cypress/support/editUtils.ts
  cypress/support/index.ts
  package.json
  src/components/item/edit/EditModal.tsx
  src/components/main/DownloadButton.tsx
  yarn.lock
Labels: chore

#1586 fix: color issues and prefix for new player
  .github/workflows/cypress.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  README.md
  package.json
  src/components/main/DownloadButton.tsx
  src/components/main/Main.tsx
  src/components/main/NewItemButton.tsx
  src/components/main/NotificationButton.tsx
  src/config/env.ts
  yarn.lock
Labels: bug :beetle:, ui
