Repository graasp/graasp-builder, pull requests merged in 2024-07, with the labels that each got.

#1316 chore(main): release 2.30.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1322 fix: warning about `UNSAFE_componentWillMount` using react-helmet-async
  package.json
  src/components/Root.tsx
  src/components/item/ItemMain.tsx
  src/components/pages/BookmarkedItemsScreen.tsx
  src/components/pages/HomeScreen.tsx
  src/components/pages/PublishedItemsScreen.tsx
  src/components/pages/RecycledItemsScreen.tsx
  yarn.lock
Labels: chore, dependencies

#1323 chore(main): release 2.31.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1340 chore(main): release 2.32.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1369 fix: no display for loading state in bookmarks, published and recycled
  src/components/layout/LoadingScreen.tsx
  src/components/pages/BookmarkedItemsScreen.tsx
  src/components/pages/PublishedItemsScreen.tsx
  src/components/pages/RecycledItemsScreen.tsx
  src/components/pages/home/HomeScreen.tsx
  src/components/pages/home/HomeScreenLoading.tsx
Labels: bug :beetle:

#1388 fix: prevent map to loop
  src/components/Root.tsx
Labels: bug :beetle:, priority

#1381 chore(main): release 2.34.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
