Repository graasp/graasp-builder, pull requests merged in 2024-03, with the labels that each got.

#1058 fix: revert previous published item layout
  src/components/common/PublishButton.tsx
  src/components/main/MainMenu.tsx
  src/langs/constants.ts
  src/langs/en.json
  src/langs/fr.json
Labels: bug :beetle:, priority

#1060 feat: add map view
  cypress/e2e/item/duplicate/duplicateItem.cy.ts
  package.json
  src/components/item/MapView.tsx
  src/components/item/header/ModeButton.tsx
  src/components/item/settings/GeolocationPicker.tsx
  src/components/item/settings/hooks.ts
  src/components/main/Items.tsx
  src/enums/itemLayoutMode.ts
  yarn.lock
Labels: feature

#1083 feat: add skeleton for modal
  src/components/main/itemSelectionModal/AccessibleNavigationTree.tsx
  src/components/main/itemSelectionModal/ChildrenNavigationTree.tsx
  src/components/main/itemSelectionModal/ItemSelectionModal.tsx
  src/components/main/itemSelectionModal/RootNavigationTree.tsx
  src/components/main/itemSelectionModal/RowMenu.tsx
  src/utils/itemSelection.ts
Labels: improvement

#1086 fix: permission function
  .github/workflows/ci.yml
  package.json
  src/utils/item.test.js
  src/utils/item.test.ts
  src/utils/item.ts
  yarn.lock
Labels: bug :beetle:

#1094 fix: rename chatbox title
  src/components/item/ItemMain.tsx
  src/langs/en.json
  src/langs/fr.json
Labels: improvement

#1113 fix: set redirection for auth signin
  cypress/e2e/authentication.cy.ts
  cypress/e2e/header.cy.ts
  cypress/support/server.ts
  src/components/App.tsx
  src/components/common/UserSwitchWrapper.tsx
  src/config/externalPaths.ts
Labels: bug :beetle:

#1120 fix: update notifs and dismiss uppy status
  src/components/Root.tsx
  src/components/file/FileDashboardUploader.tsx
  src/components/file/UppyContext.tsx
  src/components/item/header/ModeButton.tsx
  src/components/main/NewItemModal.tsx
  yarn.lock
Labels: improvement
