Repository graasp/graasp-builder, pull requests merged in 2024-08, with the labels that each got.

#1391 feat: remove aggrid and update memberships tables
  cypress/e2e/item/view/viewFolder.cy.ts
  cypress/e2e/memberships/deleteItemMembership.cy.ts
  cypress/e2e/memberships/editItemMembership.cy.ts
  package.json
  src/components/Root.tsx
  src/components/item/sharing/InvitationsTable.tsx
  src/components/item/sharing/ItemMembershipSelect.tsx
  src/components/item/sharing/ItemMembershipsTable.tsx
  src/components/item/sharing/ItemSharingTab.tsx
  src/components/item/sharing/ResendInvitation.tsx
  src/components/item/sharing/ResendInvitationRenderer.tsx
  src/components/item/sharing/TableRowDeleteButton.tsx
  src/components/item/sharing/TableRowDeleteButtonRenderer.tsx
  src/components/item/sharing/TableRowPermission.tsx
  src/components/item/sharing/TableRowPermissionRenderer.tsx
  src/components/styles.css
  src/components/table/MemberNameCellRenderer.tsx
  src/config/selectors.ts
  src/langs/ar.json
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  yarn.lock
Labels: feature

#1397 chore(main): release 2.35.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1402 chore(main): release 2.35.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1407 feat: update for item login
  cypress/e2e/invitations/createInvitation.cy.ts
  cypress/e2e/item/copy/copy.cy.ts
  cypress/e2e/item/hide/hideItem.cy.ts
  cypress/e2e/item/move/move.cy.ts
  cypress/e2e/item/publish/viewPublished.cy.ts
  cypress/e2e/item/trash/delete.cy.ts
  cypress/e2e/item/view/viewDocument.cy.ts
  cypress/e2e/item/view/viewLink.cy.ts
  cypress/e2e/memberships/createItemMembership.cy.ts
  cypress/e2e/memberships/deleteItemMembership.cy.ts
  cypress/e2e/memberships/editItemMembership.cy.ts
  cypress/e2e/memberships/viewMemberships.cy.ts
  cypress/fixtures/chatbox.ts
  cypress/fixtures/invitations.ts
  cypress/fixtures/items.ts
  cypress/fixtures/members.ts
  cypress/fixtures/memberships.ts
  cypress/support/commands.ts
  cypress/support/commands/item.ts
  cypress/support/index.ts
  cypress/support/server.ts
  cypress/support/types.ts
  package.json
  src/components/common/Chatbox.tsx
  src/components/common/DeleteButton.tsx
  src/components/common/FlagButton.tsx
  src/components/common/RecycleButton.tsx
  src/components/item/ItemMemberships.tsx
  src/components/item/copy/CopyButton.tsx
  src/components/item/edit/EditButton.tsx
  src/components/item/header/ItemHeaderActions.tsx
  src/components/item/move/MoveButton.tsx
  src/components/item/settings/ItemSettingsButton.tsx
  src/components/item/sharing/ConfirmMembership.tsx
  src/components/item/sharing/CreateItemMembershipForm.tsx
  src/components/item/sharing/InvitationsTable.tsx
  src/components/item/sharing/ItemLoginMembershipsTable.tsx
  src/components/item/sharing/ItemMembershipsTable.tsx
  src/components/item/sharing/ItemSharingTab.tsx
  src/components/item/sharing/ResendInvitation.tsx
  src/components/item/sharing/csvImport/DisplayInvitationSummary.tsx
  src/config/selectors.ts
  src/langs/en.json
  src/langs/fr.json
  src/main.tsx
  src/utils/item.test.ts
  src/utils/item.ts
  src/utils/membership.ts
  yarn.lock
Labels: feature

#1427 fix: fix post item membership
  package.json
  src/components/item/sharing/ItemMembershipsTable.tsx
  yarn.lock
Labels: bug :beetle:
