Repository graasp/graasp-builder, pull requests merged in 2024-02, with the labels that each got.

#976 fix: default route and conventions for route screens
  cypress/support/commands.ts
  package.json
  src/components/App.tsx
  src/components/RecycleBinScreen.tsx
  src/components/Root.tsx
  src/components/context/LayoutContext.tsx
  src/components/file/FileUploader.tsx
  src/components/item/ItemMain.tsx
  src/components/main/Main.tsx
  src/components/main/PublishedItems.tsx
  src/components/pages/FavoriteItemsScreen.tsx
  src/components/pages/HomeScreen.tsx
  src/components/pages/ItemScreen.tsx
  src/components/pages/PublishedItemsScreen.tsx
  src/components/pages/RecycledItemsScreen.tsx
  src/components/pages/SharedItemsScreen.tsx
  src/config/queryClient.ts
  src/config/selectors.ts
  yarn.lock
Labels: bug :beetle:

#984 feat: hide none-folder in the move modal
  package.json
  src/components/main/itemSelectionModal/AccessibleNavigationTree.tsx
  src/components/main/itemSelectionModal/ChildrenNavigationTree.tsx
  src/components/main/itemSelectionModal/RootNavigationTree.tsx
  yarn.lock
Labels: feature

#967 fix: some loaders to display data first and pagination bugs
  cypress/e2e/item/copy/listCopyItem.cy.ts
  cypress/e2e/item/delete/listRecycleItem.cy.ts
  cypress/e2e/item/pin/pinItem.cy.ts
  cypress/support/commands/navigation.ts
  src/components/item/ItemContent.tsx
  src/components/item/header/ItemHeader.tsx
  src/components/item/header/ItemHeaderActions.tsx
  src/components/main/ItemActions.tsx
  src/components/main/ItemCard.tsx
  src/components/main/ItemMenu.tsx
  src/components/main/Items.tsx
  src/components/main/ItemsTable.tsx
  src/components/pages/PublishedItemsScreen.tsx
  src/components/pages/RecycledItemsScreen.tsx
  src/components/pages/SharedItemsScreen.tsx
  src/components/table/ActionsCellRenderer.tsx
Labels: bug :beetle:

#991 fix: use 100% for crop
  src/components/common/CropModal.tsx
Labels: improvement

#992 fix: make thumbnails nice in grid view
  src/components/main/ItemCard.tsx
  src/components/table/ItemNameCellRenderer.tsx
Labels: ui

#1015 fix: update readme values
  README.md
  src/config/env.ts
Labels: documentation

#1011 fix: cant remove flavor
  package.json
  src/components/item/form/DocumentForm.tsx
  yarn.lock
Labels: bug :beetle:

#1032 fix: use esm modules for graasp dependencies
  cypress/e2e/authentication.cy.ts
  cypress/e2e/item/create/createShortcut.cy.ts
  cypress/e2e/item/edit/editApp.cy.ts
  cypress/e2e/item/edit/editDocument.cy.ts
  cypress/e2e/item/move/listMoveMultiple.cy.ts
  cypress/fixtures/documents.ts
  cypress/fixtures/files.ts
  cypress/fixtures/links.ts
  cypress/fixtures/navigationItems.ts
  cypress/support/commands.ts
  cypress/support/createUtils.ts
  cypress/support/server.ts
  cypress/support/types.ts
  cypress/support/viewUtils.ts
  package.json
  src/components/common/CookiesBanner.tsx
  src/components/common/HideButton.tsx
  src/components/context/CurrentUserContext.tsx
  src/components/item/ItemContent.tsx
  src/components/item/form/AppForm.tsx
  src/components/item/form/DocumentForm.tsx
  src/components/item/form/LinkForm.tsx
  src/components/item/publish/CustomizedTagsEdit.tsx
  src/components/item/publish/ItemPublishTab.tsx
  src/components/item/settings/GeolocationPicker.tsx
  src/components/item/settings/LinkSettings.tsx
  src/components/item/sharing/ItemSharingTab.tsx
  src/components/item/sharing/TableRowPermissionRenderer.tsx
  src/components/main/ItemsTable.tsx
  src/components/main/NewItemModal.tsx
  src/components/main/itemSelectionModal/RowMenu.tsx
  src/components/table/ItemNameCellRenderer.tsx
  src/utils/item.ts
  src/utils/itemExtra.ts
  src/utils/itemSelection.ts
  vite.config.ts
  yarn.lock
Labels: dependencies
