Repository graasp/graasp-builder, pull requests merged in 2024-10, with the labels that each got.

#1485 chore(main): release 2.42.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1511 chore(main): release 2.42.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1500 feat: add umami tags to track actions
  .github/workflows/deploy-dev.yml
  cypress/e2e/authentication.cy.ts
  cypress/e2e/header.cy.ts
  cypress/e2e/item/chatbox/chatbox.cy.ts
  cypress/e2e/memberships/deleteItemMembership.cy.ts
  cypress/support/constants.ts
  index.html
  package.json
  src/components/App.tsx
  src/components/common/SelectTypes.tsx
  src/components/common/UserSwitchWrapper.tsx
  src/components/item/ItemSearch.tsx
  src/components/main/Main.tsx
  src/components/main/MainMenu.tsx
  src/components/main/NewItemButton.tsx
  src/components/table/ShowOnlyMeButton.tsx
  src/config/selectors.ts
  yarn.lock
Labels: feature

#1514 fix: update crop modal to not inflate image sizes
  src/components/common/CropModal.tsx
Labels: bug :beetle:

#1513 chore(main): release 2.43.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1544 fix: update mui version to v6
  package.json
  src/components/item/ItemMemberships.tsx
  src/components/item/form/AppForm.tsx
  src/components/item/sharing/membershipTable/GuestItemMembershipTableRow.tsx
  src/components/main/AppCard.tsx
  src/components/table/ItemCard.tsx
  yarn.lock
Labels: dependencies

#1528 chore(main): release 2.44.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
