Repository graasp/graasp-builder, pull requests merged in 2024-04, with the labels that each got.

#1134 fix: update favicon
  index.html
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/graasp.svg
  yarn.lock
Labels: chore

#1142 fix: display interpolation data on mouse hover for chatbox name
  src/components/item/header/ItemHeaderActions.tsx
Labels: bug :beetle:

#1144 fix: update graasp ui to use improved font scale
  package.json
  yarn.lock
Labels: ui

#1153 feat: provide dynamic titles for pages
  package.json
  src/components/item/ItemMain.tsx
  src/components/pages/BookmarkedItemsScreen.tsx
  src/components/pages/HomeScreen.tsx
  src/components/pages/PublishedItemsScreen.tsx
  src/components/pages/RecycledItemsScreen.tsx
  src/components/pages/SharedItemsScreen.tsx
  yarn.lock
Labels: feature

#1184 fix: improve settings page and overall
  cypress/e2e/item/home/home.cy.ts
  cypress/e2e/item/settings/itemSettings.cy.ts
  cypress/e2e/item/view/viewThumbnails.cy.ts
  package.json
  src/components/common/MemberAvatar.tsx
  src/components/file/DropzoneHelper.tsx
  src/components/item/form/AppForm.tsx
  src/components/item/publish/CustomizedTagsEdit.tsx
  src/components/item/settings/AdminChatSettings.tsx
  src/components/item/settings/ClearChatButton.tsx
  src/components/item/settings/FileSettings.tsx
  src/components/item/settings/GeolocationPicker.tsx
  src/components/item/settings/ItemLicenseSettings.tsx
  src/components/item/settings/ItemMetadataContent.tsx
  src/components/item/settings/ItemSettingProperty.tsx
  src/components/item/settings/ItemSettings.tsx
  src/components/item/settings/ItemSettingsProperties.tsx
  src/components/item/settings/LanguageSelect.tsx
  src/components/main/ItemCard.tsx
  src/components/main/ItemsToolbar.tsx
  src/components/main/NewItemButton.tsx
  src/config/constants.ts
  src/config/selectors.ts
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  src/utils/image.ts
  yarn.lock
Labels: improvement
