Repository graasp/graasp-builder, pull requests merged in 2024-09, with the labels that each got.

#1432 fix: udpate menu icons to lucide
  src/components/Root.tsx
  src/components/main/Main.tsx
  src/components/main/MainMenu.tsx
Labels: bug :beetle:, ui

#1434 fix: update mode icon
  package.json
  src/components/item/header/ModeButton.tsx
  yarn.lock
Labels: bug :beetle:, un-released, ui

#1435 fix: update item menu icons
  package.json
  src/components/common/CollapseButton.tsx
  src/components/common/DeleteButton.tsx
  src/components/common/DuplicateButton.tsx
  src/components/common/HideButton.tsx
  src/components/common/PinButton.tsx
  src/components/common/PublishButton.tsx
  src/components/common/QRCode.tsx
  src/components/common/RestoreButton.tsx
  src/components/item/header/Actions.tsx
  src/components/item/header/ItemHeaderActions.tsx
  src/components/item/sharing/shortLink/AliasInput.tsx
  src/components/item/sharing/shortLink/ConfirmDeleteLink.tsx
  src/components/item/sharing/shortLink/ShortLinkMenu.tsx
  src/components/item/shortcut/CreateShortcutButton.tsx
  src/components/layout/Navigation.tsx
  src/components/main/ItemMenuContent.tsx
  src/components/main/NewItemButton.tsx
  src/components/main/list/SelectionToolbar.tsx
  src/config/env.ts
  src/langs/ar.json
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  yarn.lock
Labels: bug :beetle:, ui

#1418 chore(main): release 2.37.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1462 fix: update translations and dependencies
  .husky/commit-msg
  .husky/post-commit
  .husky/pre-commit
  .husky/pre-push
  cypress/e2e/item/move/move.cy.ts
  cypress/e2e/item/view/viewFolder.cy.ts
  package.json
  src/components/item/ItemContent.tsx
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  src/utils/clipboard.ts
  yarn.lock
Labels: dependencies

#1460 feat: show item login message on customer pages
  cypress/e2e/item/bookmarks/bookmarks.cy.ts
  cypress/e2e/item/home/home.cy.ts
  cypress/e2e/item/publish/viewPublished.cy.ts
  cypress/e2e/item/trash/viewTrash.cy.ts
  cypress/e2e/item/view/viewFolder.cy.ts
  package.json
  src/components/App.tsx
  src/components/Root.tsx
  src/components/common/BookmarkButton.tsx
  src/components/common/UserSwitchWrapper.tsx
  src/components/context/CurrentUserContext.tsx
  src/components/item/FolderContent.tsx
  src/components/item/ItemContent.tsx
  src/components/item/header/Actions.tsx
  src/components/layout/Navigation.tsx
  src/components/main/ItemMenuContent.tsx
  src/components/main/Main.tsx
  src/components/main/MainMenu.tsx
  src/components/pages/home/HomeScreen.tsx
  src/components/pages/item/ItemLoginWrapper.tsx
  src/components/pages/item/ItemPageLayout.tsx
  src/components/pages/item/ItemScreenLayout.tsx
  src/components/table/ItemActions.tsx
  src/config/selectors.ts
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  yarn.lock
Labels: bug :beetle:, priority

#1444 chore(main): release 2.38.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1477 chore(main): release 2.40.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1481 fix: define container for drag selection
  src/components/item/FolderContent.tsx
  src/components/main/list/ItemsTable.tsx
  src/components/main/list/SelectionContext.tsx
  src/components/main/list/useDragSelection.tsx
  src/components/pages/PageWrapper.tsx
  src/components/pages/RecycledItemsScreen.tsx
  src/components/pages/home/HomeScreen.tsx
Labels: bug :beetle:

#1483 chore(main): release 2.41.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1487 fix: remove usage of `false` in component return
  cypress/support/commands.ts
  cypress/support/server.ts
  src/components/alerts/MemberValidationBanner.tsx
  src/components/common/ShowChatboxButton.tsx
  src/components/item/sharing/csvImport/DisplayInvitationSummary.tsx
  src/components/main/MainMenu.tsx
Labels: chore
